### ISSUE TITLE
console error, course wont build

### ISSUE THREAD

**Issue by robmausser** [deltanet/adapt-animate#25]
VM5391 adapt.min.js:12550 Uncaught TypeError: Cannot read property '_custom' of undefined
    at n.render (VM5391 adapt.min.js:12550)
    at n.initialize (VM5391 adapt.min.js:12531)
    at n.e.View (VM5380 backbone.min.js:2)
    at new n (VM5380 backbone.min.js:2)
    at Object.onComponentReady (VM5391 adapt.min.js:12844)
    at _ (VM5380 backbone.min.js:2)
    at m (VM5380 backbone.min.js:2)
    at f (VM5380 backbone.min.js:2)
    at n.u.trigger (VM5380 backbone.min.js:2)
    at n.<anonymous> (VM5391 adapt.min.js:3908)
render @ VM5391 adapt.min.js:12550
initialize @ VM5391 adapt.min.js:12531
e.View @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
onComponentReady @ VM5391 adapt.min.js:12844
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:3908
(anonymous) @ VM5379 underscore.min.js:5
setTimeout (async)
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
N @ VM5379 underscore.min.js:5
a @ VM5379 underscore.min.js:5
render @ VM5391 adapt.min.js:3903
initialize @ VM5391 adapt.min.js:3883
e.View @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
addChildren @ VM5391 adapt.min.js:3954
postRender @ VM5391 adapt.min.js:3890
(anonymous) @ VM5391 adapt.min.js:3907
(anonymous) @ VM5379 underscore.min.js:5
setTimeout (async)
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
N @ VM5379 underscore.min.js:5
a @ VM5379 underscore.min.js:5
render @ VM5391 adapt.min.js:3903
initialize @ VM5391 adapt.min.js:3883
e.View @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
addChildren @ VM5391 adapt.min.js:3954
postRender @ VM5391 adapt.min.js:3890
(anonymous) @ VM5391 adapt.min.js:3907
(anonymous) @ VM5379 underscore.min.js:5
setTimeout (async)
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
N @ VM5379 underscore.min.js:5
a @ VM5379 underscore.min.js:5
render @ VM5391 adapt.min.js:3903
initialize @ VM5391 adapt.min.js:3883
ArticleView.initialize @ VM5391 adapt.min.js:13410
ArticleView.initialize @ VM5391 adapt.min.js:15056
e.View @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
addChildren @ VM5391 adapt.min.js:3954
postRender @ VM5391 adapt.min.js:3890
(anonymous) @ VM5391 adapt.min.js:3907
(anonymous) @ VM5379 underscore.min.js:5
setTimeout (async)
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
N @ VM5379 underscore.min.js:5
a @ VM5379 underscore.min.js:5
render @ VM5391 adapt.min.js:3903
initialize @ VM5391 adapt.min.js:3883
e.View @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:4374
N @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:248
setTimeout (async)
end @ VM5391 adapt.min.js:245
N @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
queue @ VM5391 adapt.min.js:266
updateLocation @ VM5391 adapt.min.js:4545
(anonymous) @ VM5391 adapt.min.js:4367
N @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:248
setTimeout (async)
end @ VM5391 adapt.min.js:245
N @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
queue @ VM5391 adapt.min.js:266
removeViews @ VM5391 adapt.min.js:4400
handleId @ VM5391 adapt.min.js:4361
handleRoute @ VM5391 adapt.min.js:4263
execute @ VM5380 backbone.min.js:2
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5380 backbone.min.js:2
h.some.h.any @ VM5379 underscore.min.js:5
loadUrl @ VM5380 backbone.min.js:2
start @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:417
deferUntilCompletionChecked @ VM5391 adapt.min.js:332
Adapt.initialize @ VM5391 adapt.min.js:411
triggerInitialize @ VM5391 adapt.min.js:23711
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:248
setTimeout (async)
end @ VM5391 adapt.min.js:245
N @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5391 adapt.min.js:18569
(anonymous) @ VM5391 adapt.min.js:18609
restoreSessionState @ VM5391 adapt.min.js:18618
initialize @ VM5391 adapt.min.js:18566
(anonymous) @ VM5391 adapt.min.js:282
(anonymous) @ VM5379 underscore.min.js:5
setTimeout (async)
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
N @ VM5379 underscore.min.js:5
a @ VM5379 underscore.min.js:5
for @ VM5391 adapt.min.js:281
app:dataReady @ VM5391 adapt.min.js:18941
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
triggerDataReady @ VM5391 adapt.min.js:23697
(anonymous) @ VM5391 adapt.min.js:23671
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:248
setTimeout (async)
end @ VM5391 adapt.min.js:245
N @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
queue @ VM5391 adapt.min.js:266
Adapt.checkDataIsLoaded @ VM5391 adapt.min.js:23670
(anonymous) @ VM5391 adapt.min.js:23741
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
loadedData @ VM5391 adapt.min.js:629
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
reset @ VM5380 backbone.min.js:2
t.success @ VM5380 backbone.min.js:2
u @ VM5372 jquery.min.js:2
fireWith @ VM5372 jquery.min.js:2
k @ VM5372 jquery.min.js:2
(anonymous) @ VM5372 jquery.min.js:2
load (async)
send @ VM5372 jquery.min.js:2
ajax @ VM5372 jquery.min.js:2
e.ajax @ VM5380 backbone.min.js:2
e.sync @ VM5380 backbone.min.js:2
sync @ VM5380 backbone.min.js:2
fetch @ VM5380 backbone.min.js:2
initialize @ VM5391 adapt.min.js:619
e.Collection @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
Adapt.loadCourseData @ VM5391 adapt.min.js:23768
onLanguageChange @ VM5391 adapt.min.js:23798
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
set @ VM5380 backbone.min.js:2
set @ VM5391 adapt.min.js:9
onLoadCourseData @ VM5391 adapt.min.js:23817
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:1776
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:248
setTimeout (async)
end @ VM5391 adapt.min.js:245
N @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
queue @ VM5391 adapt.min.js:266
(anonymous) @ VM5391 adapt.min.js:1771
t.success @ VM5380 backbone.min.js:2
u @ VM5372 jquery.min.js:2
fireWith @ VM5372 jquery.min.js:2
k @ VM5372 jquery.min.js:2
(anonymous) @ VM5372 jquery.min.js:2
load (async)
send @ VM5372 jquery.min.js:2
ajax @ VM5372 jquery.min.js:2
e.ajax @ VM5380 backbone.min.js:2
e.sync @ VM5380 backbone.min.js:2
sync @ VM5380 backbone.min.js:2
fetch @ VM5380 backbone.min.js:2
initialize @ VM5391 adapt.min.js:1767
e.Model @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
onBuildDataLoaded @ VM5391 adapt.min.js:23823
(anonymous) @ VM5380 backbone.min.js:2
(anonymous) @ VM5379 underscore.min.js:5
_ @ VM5380 backbone.min.js:2
m @ VM5380 backbone.min.js:2
f @ VM5380 backbone.min.js:2
u.trigger @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:877
N @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
(anonymous) @ VM5379 underscore.min.js:5
t.success @ VM5380 backbone.min.js:2
u @ VM5372 jquery.min.js:2
fireWith @ VM5372 jquery.min.js:2
k @ VM5372 jquery.min.js:2
(anonymous) @ VM5372 jquery.min.js:2
load (async)
send @ VM5372 jquery.min.js:2
ajax @ VM5372 jquery.min.js:2
e.ajax @ VM5380 backbone.min.js:2
e.sync @ VM5380 backbone.min.js:2
sync @ VM5380 backbone.min.js:2
fetch @ VM5380 backbone.min.js:2
initialize @ VM5391 adapt.min.js:874
e.Model @ VM5380 backbone.min.js:2
n @ VM5380 backbone.min.js:2
(anonymous) @ VM5391 adapt.min.js:23647
execCb @ VM5371 require.min.js:29
check @ VM5371 require.min.js:18
(anonymous) @ VM5371 require.min.js:22
(anonymous) @ VM5371 require.min.js:7
(anonymous) @ VM5371 require.min.js:23
y @ VM5371 require.min.js:6
emit @ VM5371 require.min.js:23
check @ VM5371 require.min.js:19
(anonymous) @ VM5371 require.min.js:22
(anonymous) @ VM5371 require.min.js:7
(anonymous) @ VM5371 require.min.js:23
y @ VM5371 require.min.js:6
emit @ VM5371 require.min.js:23
check @ VM5371 require.min.js:19
(anonymous) @ VM5371 require.min.js:22
(anonymous) @ VM5371 require.min.js:7
(anonymous) @ VM5371 require.min.js:23
y @ VM5371 require.min.js:6
emit @ VM5371 require.min.js:23
check @ VM5371 require.min.js:19
(anonymous) @ VM5371 require.min.js:22
(anonymous) @ VM5371 require.min.js:7
(anonymous) @ VM5371 require.min.js:23
y @ VM5371 require.min.js:6
emit @ VM5371 require.min.js:23
check @ VM5371 require.min.js:19
enable @ VM5371 require.min.js:23
init @ VM5371 require.min.js:16
I @ VM5371 require.min.js:13
completeLoad @ VM5371 require.min.js:28
onScriptLoad @ VM5371 require.min.js:29
load (async)
g.load @ VM5371 require.min.js:34
load @ VM5371 require.min.js:29
load @ VM5371 require.min.js:17
fetch @ VM5371 require.min.js:17
check @ VM5371 require.min.js:17
enable @ VM5371 require.min.js:23
enable @ VM5371 require.min.js:27
(anonymous) @ VM5371 require.min.js:22
(anonymous) @ VM5371 require.min.js:7
y @ VM5371 require.min.js:6
enable @ VM5371 require.min.js:21
enable @ VM5371 require.min.js:27
(anonymous) @ VM5371 require.min.js:22
(anonymous) @ VM5371 require.min.js:7
y @ VM5371 require.min.js:6
enable @ VM5371 require.min.js:21
enable @ VM5371 require.min.js:27
(anonymous) @ VM5371 require.min.js:22
(anonymous) @ VM5371 require.min.js:7
y @ VM5371 require.min.js:6
enable @ VM5371 require.min.js:21
init @ VM5371 require.min.js:16
(anonymous) @ VM5371 require.min.js:26
setTimeout (async)
g.nextTick @ VM5371 require.min.js:32
m @ VM5371 require.min.js:26
requirejs @ VM5371 require.min.js:32
(anonymous) @ VM5391 adapt.min.js:23612
Show 73 more frames
VM5391 adapt.min.js:12106 Uncaught TypeError: Cannot read property '_custom' of undefined
    at n.render (VM5391 adapt.min.js:12106)
    at n.<anonymous> (VM5380 backbone.min.js:2)
    at n.<anonymous> (VM5379 underscore.min.js:5)
    at _ (VM5380 backbone.min.js:2)
    at m (VM5380 backbone.min.js:2)
    at f (VM5380 backbone.min.js:2)
    at n.u.trigger (VM5380 backbone.min.js:2)
    at n.<anonymous> (VM5391 adapt.min.js:4153)
    at N (VM5379 underscore.min.js:5)
    at VM5379 underscore.min.js:5

**Comment by RobertPeek** [comment]
@robmausser does the latest version v2.2.2 resolve this? There have been a lot of changes/updates since this post.
